version: '3.9'

services:
  fresns.postgres:
    container_name: fs.database
    image: postgres:latest
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-6432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'fresns-postgres:/var/lib/postgresql/data'
    networks:
      - fresns
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "-q",
        "-d",
        "${DB_DATABASE}",
        "-U",
        "${DB_USERNAME}"
      ]
      retries: 3
      timeout: 5s

networks:
  fresns:
    driver: bridge

volumes:
  fresns-postgres:
    driver: local
